on:
  issues:
    types:
      - labeled
jobs:
  transfer_issue:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        router:
          - confirmed-dev:wotr-mod
          - confirmed-build:botr
    steps:
    - name: Transfer Issue & Create Stub
      uses: lando/transfer-issue-action@v2
      with:
        token: ${{ secrets.SECRET_TOKEN }}
        router: ${{ matrix.router }}
        create_stub: true
